### ISSUE TITLE
Add recommendations

### ISSUE THREAD

**Issue by mulholio** [eat-well/eatwell-web#1]
Still unsure precisely what we want this to look like

**Comment by WhiT3Kr0w** [comment]
For now we only need to add a sql query to input data into the DB. We can probably discuss data validation later.

I've added a couple of repeatable fields in the page to get the foods and recommendations. We can use these as input for the recommendations. 
We also need the login implementation so that we can use a contributor/nutritionist ID when storing the records.

**Comment by WhiT3Kr0w** [comment]
feature/1-add_recommendations

**Comment by WhiT3Kr0w** [comment]
Done
